export const FUNDERS = [
  "Spanish Government",
  "Valencian Government",
  "Jaume I University",
  "European Comission",
  "Companies",
  "Group",
];

export const PROJECTS = [
    {
    startdate: "01-01-2025",
    enddate: "28-2-2026",
    call: "ConfIA",
    shortname: "ConfIA",
    name: "[Erasmus+ SEEN] Social Entrepreneurship Ecosystems Network.",
    grant: 90000,
    link: "",
    image: "confia.webp",
    funder: "Valencian Government",
    line: "dam",
  },

  {
    startdate: "01-09-2024",
    enddate: "31-08-2026",
    call: "SEEN",
    shortname: "SEEN",
    name: "[Erasmus+ SEEN] Social Entrepreneurship Ecosystems Network.",
    grant: 400000,
    link: "https://www.linkedin.com/company/seen-project/",
    image: "seen.webp",
    funder: "European Comission",
    line: "dam",
  },
  {
    startdate: "01-09-2024",
    enddate: "31-08-2028",
    call: "CIPROM-2023-48",
    shortname: "PROMETEO",
    name: "[PROMETEO-EASIER] Interacción social aumentada a través de las realidades extendidas",
    grant: 102500,
    link: "https://aplicat.upv.es/exploraupv/ficha-proyecto/proyecto/20240714",
    image: "prometeo.webp",
    funder: "Valencian Government",
    line: "aai",
  },
];

export const PAST_PROJECTS = [
  {
    startdate: "01-02-2025",
    enddate: "28-02-2026",
    call: "INREIA/2024/30",
    shortname: "CONFIA",
    name: "Consultor Finanzas con IA",
    grant: 89606,
    link: "",
    image: "confia.webp",
    funder: "Valencian Government",
    line: "aai",
  },
  {
    startdate: "01-07-2025",
    enddate: "31-12-2025",
    call: "INNDIH-Symplia",
    shortname: "I-S",
    name: "Adagio: Reconocimiento del habla para personas con dificultades",
    grant: 10872,
    link: "",
    image: "symplia.webp",
    funder: "European Comission",
    line: "aig",
  },
  {
    startdate: "01-07-2025",
    enddate: "31-12-2025",
    call: "INNDIH-Improven",
    shortname: "I-I",
    name: "Asistente conversacional para la gestión del conocimiento en consultoría mediante LLMs",
    grant: 10872,
    link: "",
    image: "improven.webp",
    funder: "European Comission",
    line: "aai",
  },
  {
    startdate: "01-01-2025",
    enddate: "30-06-2025",
    call: "INNDIH-Cebimat",
    shortname: "I-C",
    name: "Desarrollo de herramienta digital para optimización de la calidad de las fotografías de muestras",
    grant: 10872,
    link: "",
    image: "cebimat.webp",
    funder: "European Comission",
    line: "aai",
  },
  {
    startdate: "01-09-2022",
    enddate: "31-08-2025",
    call: "PID2021-122642OB-C44",
    shortname: "INDRI",
    name: "Localization and integrated sensing for digital human activity tracing",
    grant: 115071,
    link: "https://geintra-uah.org/projects/localizacion-y-deteccion-integrada-seguimiento-digital-actividad-humana-indri",
    image: "indri.webp",
    funder: "Spanish Government",
    line: "sds",
  },

  {
    startdate: "01-01-2023",
    enddate: "31-12-2025",
    call: "UJI-A2022-12",
    shortname: "NEURO-ML",
    name: "Machine learning through bio-inspired models (and vice versa)",
    grant: 19825,
    link: "https://www.uji.es/serveis/ocit/base/grupsinvestigacio/detall?codi=329",
    image: "neuroml.webp",
    funder: "Jaume I University",
    line: "dam",
  },

  {
    startdate: "01-01-2023",
    enddate: "31-08-2025",
    call: "101061424 (HORIZON-CL2-2021-TRANSFORMATIONS-01)",
    shortname: "e-DIPLOMA",
    name: "Electronic, Didactive and Innovative PLatform based On Multimedia Assets",
    grant: 3000000,
    link: "https://e-diplomaproject.eu/",
    image: "ediploma.webp",
    funder: "European Comission",
    line: "aai",
  },
  {
    startdate: "01-01-2023",
    enddate: "31-12-2025",
    call: "COMCUANTICA/007",
    shortname: "QUANTwin",
    name: "Modelo de gemelo digital cuántico híbrido para el estudio de la influencia de los daños por erosión en el rendimiento de los aerogeneradores",
    grant: 102500,
    link: "https://panorama.upv.es/cat/ipublic/item/10075751",
    image: "quantwin.webp",
    funder: "Valencian Government",
    line: "dam",
  },
  {
    startdate: "01-01-2023",
    enddate: "31-12-2025",
    call: "RED2022-134355-T",
    shortname: "REPNIN++",
    name: "Red de posicionamiento y navegación en interiores y exteriores restringidos y sus aplicaciones.",
    link: "https://repnin.web.uah.es/",
    image: "repnin.webp",
    funder: "Group",
    line: "sds",
  },
  {
    startdate: "01-01-2023",
    enddate: "31-12-2024",
    call: "CIGE-2022-066",
    shortname: "CIGE",
    name: "Un Enfoque Bioplausible en la Intersección de Matemáticas e Inteligencia Artificial",
    grant: 20000,
    link: "https://ceice.gva.es/es/web/ciencia/convocatories_2022",
    image: "cige.webp",
    funder: "Valencian Government",
    line: "dam",
  },
  {
    startdate: "09-10-2020",
    enddate: "09-04-2022",
    call: "BBVA2020",
    shortname: "BBVA2020",
    name: "Ciencias de Datos e Inteligencia Artificial para el apoyo en la toma de decisiones de políticas de salud pública. Ayudas Fundación BBVA a equipos de Investigación Científica SARS‐CoV‐2 y COVID‐19",
    grant: 150000,
    link: "https://www.fbbva.es/ayudas/ayudas-equipos-investigacion-cientifica-2020-covid19/",
    image: "bbva20.webp",
    funder: "Companies",
    line: "dam",
  },
  {
    startdate: "01-04-2024",
    enddate: "31-12-2024",
    call: "Catness",
    shortname: "CTN-1",
    name: "Automatización de procesos de porting",
    link: "https://catnessgames.com/es/",
    image: "catness.webp",
    funder: "Companies",
    line: "aai",
  },
  {
    startdate: "01-01-2024",
    enddate: "31-12-2024",
    call: "DIRECT-Gest",
    shortname: "DIR-GEST",
    name: "[UJISABIO 2023] Desarrollo de las habilidades y competencias directivas de las enfermeras a través de un videojuego como herramienta de aprendizaje de la gestión sanitaria.",
    grant: 5000,
    link: "https://unisalut.uji.es/ayudas/",
    image: "directgest.webp",
    funder: "Valencian Government",
    line: "gvai",
  },
  {
    startdate: "01-01-2024",
    enddate: "31-12-2024",
    call: "CC-IA",
    shortname: "CC-IA",
    name: "[ILISABIO 2023] Implementación de la Inteligencia Artificial y el procesamiento automático de imágenes para la valoración de la composición corporal e inflamación sistémica en cáncer colorrectal.",
    grant: 20000,
    link: "https://unisalut.uji.es/ayudas/",
    image: "ccia.webp",
    funder: "Valencian Government",
    line: "aai",
  },
];
