export const SEMINARS = [
  /* {
    title: "",
    date: "",
    location: "",
    speaker: "",
    speakerUrl: "",
    image: "",
    }*/
   {
    title: "RTT-based Indoor Positioning",
    date: "01-10-2025 15:05",
    location: "NB4302DL",
    speaker: "Raul Montoliu",
    speakerUrl: "https://www.raulmontoliu.com/",
    image: "wam011025.webp",
   },

  {
    title: "Introducción a la IA generativa",
    date: "24-09-2025 15:05",
    location: "NB4302DL",
    speaker: "Emilio Sansano",
    image: "wam240925.webp",
   },
  {
    title: "AI for Cultural Heritage",
    date: "12-02-2025 15:30",
    location: "NB4302DL",
    speaker: "Alessio Ferrato",
    speakerUrl: "https://www.alessioferrato.it/",
    image: "alessio-120225.webp",
  },
  {
    title:
      "What is beautiful is still good: the attractiveness halo effect in the era of beauty filters",
    date: "04-12-2024 14:30",
    location: "NB4302DL",
    speaker: "Marina García",
    speakerUrl: "",
    image: "marina-041224.webp",
  },
  {
    title: "Understanding Human Perception of Rotations in Natural Images",
    date: "27-11-2024 14:30",
    location: "NB4302DL",
    speaker: "David Agost",
    speakerUrl: "",
    image: "david-271124.webp",
  },
  {
    title: "Approaches to Error Bound Estimation in Indoor Positioning",
    date: "06-11-2024 14:30",
    location: "NB4302DL",
    speaker: "Cristian Valero",
    speakerUrl: "",
    image: "cristian-061124.webp",
  },
  {
    title: "A game for hospital management simulation",
    date: "30-10-2024 14:30",
    location: "NB4302DL",
    speaker: "Gonzalo Ramia",
    speakerUrl: "",
    image: "gonzalo-301024.webp",
  },
  {
    title: "Obtaining Good Recommendations for Students",
    date: "23-10-2024 14:30",
    location: "NB4302DL",
    speaker: "Alex Martínez",
    speakerUrl: "",
    image: "alex-231024.webp",
  },
  {
    title: "Archetypal Analysis: Characterizing data by 'extremes'",
    date: "16-10-2024 14:30",
    location: "NB4302DL",
    speaker: "Aleix Alcacer Sales",
    speakerUrl: "https://www.aleixalcacer.com/",
    image: "aleix-161024.webp",
  },
  {
    title:
      "Hybridizing Collaborative Filtering and Knowledge-based Filtering for Recommender Systems",
    date: "19-06-2024 15:00",
    location: "NB4302DL",
    speaker: "Alex Martínez",
    speakerUrl: "",
    image: "alex-190624.webp",
  },
  {
    title: "Introduction to information theory",
    date: "12-06-2024 15:00",
    location: "NB4302DL",
    speaker: "Marina Martínez",
    speakerUrl: "",
    image: "marina-120624.webp",
  },
  {
    title: "Sensorising team sports and data analysis",
    date: "05-06-2024 15:00",
    location: "NB4302DL",
    speaker: "Raúl Montoliu",
    speakerUrl: "",
    image: "raul-050624.webp",
  },
  {
    title: "Image Processing: The Fourier Transform",
    date: "22-05-2024 15:00",
    location: "NB4302DL",
    speaker: "Emilio Sansano",
    speakerUrl: "",
    image: "emilio-220524.webp",
  },
  {
    title:
      "Definition and analysis of strategic predictive indicators for social networks",
    date: "08-05-2024 15:00",
    location: "NB4302DL",
    speaker: "Indira Lanza Cruz",
    speakerUrl: "",
    image: "indira-080524.webp",
  },
  {
    title: "Functional connectivity: A brief introduction",
    date: "24-04-2024 15:00",
    location: "NB4302DL",
    speaker: "Jaume Usó",
    speakerUrl: "",
    image: "jaume-240424.webp",
  },
  {
    title: "Error bound estimation",
    date: "17-04-2024 15:00",
    location: "NB4302DL",
    speaker: "Cristian Valero",
    speakerUrl: "",
    image: "cristian-170424.webp",
  },
  {
    title: "How to Set Up a Psychophysical Experiment",
    date: "13-03-2024 15:00",
    location: "TI1113",
    speaker: "David Agost",
    speakerUrl: "",
    image: "david-130324.webp",
  },
  {
    title:
      "AI for Education: From Predicting Student Performance to Recommend Educational Resources",
    date: "28-02-2024 15:00",
    location: "TI1113",
    speaker: "Alex Martínez",
    speakerUrl: "",
    image: "alex-280224.webp",
  },
  {
    title: "Monitoring and positioning",
    date: "21-02-2024 15:00",
    location: "TI1113",
    speaker: "Javier Gaviña",
    speakerUrl: "",
    image: "javier-210224.webp",
  },
  {
    title: "Discovering routine behaviour from time series data",
    date: "14-02-2024 14:30",
    location: "TI1113",
    speaker: "Raúl Montoliu",
    speakerUrl: "",
    image: "raul-140224.webp",
  },
  {
    title: "Closing the gap between human and machine vision",
    date: "07-02-2024 14:30",
    location: "TI1113",
    speaker: "Emilio Sansano",
    speakerUrl: "",
    image: "emilio-070224.webp",
  },
  {
    title: "From Biology to Machine Learning and vice versa",
    date: "31-01-2024 14:30",
    location: "TI1113",
    speaker: "Marina Martínez",
    speakerUrl: "",
    image: "marina-310124.webp",
  },
];
